Added Used-defined APIs template
SkylineCommunications/Skyline.DataMiner.VisualStudioTemplates.Internal pull request #11
Opened 2024-01-09 13:20 UTC by JorgeFilipeDias

User-defined APIs template

2024-01-09 13:27 UTC, MichielOda requested changes

2024-01-09 13:27 UTC, MichielOda commented on working/templates/userdefinedAPIsolution/$SCRIPTNAME$_1/$SCRIPTNAME$_1.cs
> +		}
```suggestion
		{
			// Add custom code here
			
			return new ApiTriggerOutput
			{
				ResponseBody = "Succeeded",
				ResponseCode = (int)StatusCode.Ok
			};
		}
```

2024-01-09 13:27 UTC, MichielOda commented on working/templates/userdefinedAPIsolution/$SCRIPTNAME$_1/$SCRIPTNAME$_1.cs
> +		}
This way it's in line with the snippet that is part of DIS. Maybe double check if the syntax if still fully correct.

2024-01-09 13:46 UTC, JorgeFilipeDias commented on working/templates/userdefinedAPIsolution/$SCRIPTNAME$_1/$SCRIPTNAME$_1.cs
> +		}
Added the snippet from skyline docs

2024-01-11 08:07 UTC, MichielOda requested changes

2024-01-11 08:07 UTC, MichielOda commented on .gitignore
> +/working/.vs/*
```suggestion
**/.vs/*
```

2024-01-11 08:07 UTC, MichielOda commented on README.md
> +Template that creates a new User-defined API automation script Visual Studio solution.
```suggestion
Template that creates a new User-Defined API Automation script Visual Studio solution.
```

2024-01-11 08:07 UTC, MichielOda commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +  "name": "DataMiner User-defined APIs Automation Script Solution",
```suggestion
  "name": "DataMiner User-Defined APIs Automation Script Solution",
```

2024-01-11 08:55 UTC, Seppe-Vanhee commented on working/templates/userdefinedAPIsolution/$SCRIPTNAME$_1/$SCRIPTNAME$_1.cs
> +		/// <param name="requestData">Hold the API request data.</param>
```suggestion
		/// <param name="requestData">Holds the API request data.</param>
```

2024-01-11 10:18 UTC, MichielOda reviewed
Look alright to me for the internal version.
@PedroDebevere, could you have a double look?

2024-01-11 10:18 UTC, MichielOda commented on .gitignore
@PedroDebevere Not sure if we actually want this .gitignore? As this contains items specific to Skyline. Also (as this PR will eventually also end up in the main repo (not the Internal one) we want to give the users the choice of what they put in the .gitignore?

2024-01-15 07:42 UTC, PedroDebevere commented on .gitignore
gitignore can be removed

2024-01-15 07:42 UTC, PedroDebevere commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +  "identity": "Skyline.DataMiner.UserDefinedApi.AutomationScript.Solution.Template",
```suggestion
  "identity": "Skyline.DataMiner.UserDefinedApi.Solution.Template",
```

2024-01-15 07:42 UTC, PedroDebevere commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +  "name": "DataMiner User-Defined APIs Automation Script Solution",
```suggestion
  "name": "DataMiner User-Defined API Solution",
```

2024-01-15 07:42 UTC, PedroDebevere commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +  "shortName": "dataminer-user-defined-api-automation-solution",
```suggestion
  "shortName": "dataminer-user-defined-api-solution",
```

2024-01-15 07:42 UTC, PedroDebevere commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +  "sourceName": "SkylineDataMinerUserDefinedApiAutomationScriptSolutionTemplate",
```suggestion
  "sourceName": "SkylineDataMinerUserDefinedApiSolutionTemplate",
```

2024-01-15 15:12 UTC, JorgeFilipeDias commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +	"F2683535-3B81-4454-9E99-120E5016BBCE"
They are used in the .sln file, I've copy pasted from the Automation Script template, should we create new Guids?

2024-01-15 15:16 UTC, JorgeFilipeDias commented on .gitignore
Removed file

2024-01-16 08:11 UTC, PedroDebevere commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +	"F2683535-3B81-4454-9E99-120E5016BBCE"
Last GUID can be removed, it is not present in the sln file (the GUIDs mentioned in this file denote the GUIDs that need to be replaced by new GUIDs when creating a new solution using this template).

2024-01-16 10:24 UTC, JorgeFilipeDias commented on working/templates/userdefinedAPIsolution/.template_config/template.json
> +	"F2683535-3B81-4454-9E99-120E5016BBCE"
Removed the last GUID

2024-01-16 10:27 UTC, PedroDebevere approved these changes

2024-01-16 12:20 UTC, merged