Support DxM solutions
SkylineCommunications/Skyline.DataMiner.VisualStudioTemplates.Internal pull request #12
Opened 2024-04-08 12:25 UTC by janstaelensskyline

2024-04-10 10:14 UTC, MichielOda requested changes

2024-04-10 10:14 UTC, MichielOda commented on working/templates/dxmsolution/InstallerProject/InstallerProject.wixproj
> +    <PackageReference Include="WixToolset.Heat" Version="4.0.5" />
Version 5.0.0 has been released recently. Not sure if that one can be used already or not.

2024-04-10 10:14 UTC, MichielOda commented on working/templates/dxmsolution/ServiceProject/Worker.cs
Indentation isn't correct.

2024-04-10 11:13 UTC, janstaelensskyline commented on working/templates/dxmsolution/InstallerProject/InstallerProject.wixproj
> +    <PackageReference Include="WixToolset.Heat" Version="4.0.5" />
Let's wait with this. It's a Major version change from last week, breaking changes that I'm not sure apply here or not. We've done all QA with the WiX 4  so far and can guarantee a stable release with this for now.

2024-04-10 11:15 UTC, janstaelensskyline commented on working/templates/dxmsolution/ServiceProject/Worker.cs
updated

2024-04-10 12:15 UTC, MichielOda approved these changes

2024-04-10 13:50 UTC, MichielOda requested changes

2024-04-10 13:50 UTC, MichielOda commented on working/templates/dxmsolution/InstallerProject/InstallerProject.wixproj
> +	  </ItemGroup>
Indentation is different

2024-04-10 13:50 UTC, MichielOda commented on working/templates/dxmsolution/ServiceProject/ServiceProject.csproj
> +	<ServerGarbageCollection>true</ServerGarbageCollection>
Indentation is different

2024-04-10 13:50 UTC, MichielOda commented on working/templates/dxmsolution/ServiceProject/Properties/launchSettings.json
Not sure if these launch settings need to be part of the template.

2024-04-11 09:31 UTC, janstaelensskyline commented on working/templates/dxmsolution/ServiceProject/Properties/launchSettings.json
They are also part of the official microsoft template for background worker service.

2024-04-11 09:38 UTC, janstaelensskyline commented on working/templates/dxmsolution/InstallerProject/InstallerProject.wixproj
> +	  </ItemGroup>
Used notepad++ pretty print. Updated.

2024-04-11 09:38 UTC, janstaelensskyline commented on working/templates/dxmsolution/ServiceProject/ServiceProject.csproj
> +	<ServerGarbageCollection>true</ServerGarbageCollection>
Used notepad++ pretty print. Updated.

2024-04-15 09:59 UTC, MichielOda approved these changes

2024-04-15 14:40 UTC, merged